### ISSUE TITLE
CSS variable arbitrary properties are treated as the same thing and merged

### ISSUE THREAD

**Issue by jacksleight** [gehrisandro/tailwind-merge-php#8]
If you define multiple CSS variables using [arbitrary properties](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties) they are treated as the same thing, so merging this:

```
[--main:red] [--fill:blue]
```

Results in:

```
[--fill:blue]
```

These aren't setting the same thing so shouldn't be merged.

Running version 1.0.0.

**Comment by gehrisandro** [comment]
Hi @jacksleight 

Could you please provide a full example here: https://play.tailwindcss.com/

**Comment by jacksleight** [comment]
@gehrisandro Sure!

Here's an example: https://play.tailwindcss.com/04LzzuvAVY

Let's say you've built a reusable component class:

```css
@layer components {
  .box {
    color: var(--main, white);
    background-color: var(--fill, black);
    width: 100px;
    height: 100px;
    margin-bottom: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
  }
}
```

That you want to theme with CSS variables:

```html
<div class="box [--main:dodgerblue] [--fill:navy]">
 1
</div>

<div class="box [--main:goldenrod] [--fill:darkred]">
 2
</div>
```

When `box [--main:dodgerblue] [--fill:navy]` is passed through tailwind merge it comes out as `box [--fill:navy]` because it thinks the two classes are setting the same property, but they're not.
